# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestHotmart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestHotmart
	pod ‘JSONJoy-Swift’
	pod 'SlideMenuControllerSwift'


  target 'TestHotmartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestHotmartUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
